language: node_js

node_js:
  - "node"

cache: yarn

script: yarn build

branches:
  only:
    - master

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: spin-to-win
  target-branch: gh-pages
  on:
    branch: master
